"""empty message

Revision ID: 4f30114c1771
Revises: 86c701f95442
Create Date: 2021-03-01 23:01:12.295829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f30114c1771'
down_revision = '86c701f95442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formacoes_academicas', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'formacoes_academicas', 'usuarios', ['usuario_id'], ['id'])
    op.add_column('formacoes_complementares', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'formacoes_complementares', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'formacoes_complementares', type_='foreignkey')
    op.drop_column('formacoes_complementares', 'usuario_id')
    op.drop_constraint(None, 'formacoes_academicas', type_='foreignkey')
    op.drop_column('formacoes_academicas', 'usuario_id')
    # ### end Alembic commands ###
