"""empty message

Revision ID: 86c701f95442
Revises: aaeffbdf79a5
Create Date: 2021-03-01 22:57:32.337277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86c701f95442'
down_revision = 'aaeffbdf79a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividades_profissionais', sa.Column('atuacao_profissional_id', sa.Integer(), nullable=False))
    op.add_column('atividades_profissionais', sa.Column('descricao', sa.String(length=200), nullable=False))
    op.drop_constraint('atividades_profissionais_ibfk_1', 'atividades_profissionais', type_='foreignkey')
    op.create_foreign_key(None, 'atividades_profissionais', 'atuacoes_profissionais', ['atuacao_profissional_id'], ['id'])
    op.drop_column('atividades_profissionais', 'atuacao_profissionais_id')
    op.add_column('formacoes_academicas', sa.Column('trabalho_conclusao', sa.String(length=200), nullable=True))
    op.drop_constraint('formacoes_academicas_ibfk_2', 'formacoes_academicas', type_='foreignkey')
    op.drop_column('formacoes_academicas', 'tabalho_conclusao')
    op.drop_column('formacoes_academicas', 'usuario_id')
    op.add_column('formacoes_complementares', sa.Column('inicio', sa.Date(), nullable=False))
    op.add_column('formacoes_complementares', sa.Column('termino', sa.Date(), nullable=True))
    op.drop_constraint('formacoes_complementares_ibfk_2', 'formacoes_complementares', type_='foreignkey')
    op.drop_column('formacoes_complementares', 'usuario_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formacoes_complementares', sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('formacoes_complementares_ibfk_2', 'formacoes_complementares', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('formacoes_complementares', 'termino')
    op.drop_column('formacoes_complementares', 'inicio')
    op.add_column('formacoes_academicas', sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('formacoes_academicas', sa.Column('tabalho_conclusao', mysql.VARCHAR(length=200), nullable=False))
    op.create_foreign_key('formacoes_academicas_ibfk_2', 'formacoes_academicas', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('formacoes_academicas', 'trabalho_conclusao')
    op.add_column('atividades_profissionais', sa.Column('atuacao_profissionais_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atividades_profissionais', type_='foreignkey')
    op.create_foreign_key('atividades_profissionais_ibfk_1', 'atividades_profissionais', 'atuacoes_profissionais', ['atuacao_profissionais_id'], ['id'])
    op.drop_column('atividades_profissionais', 'descricao')
    op.drop_column('atividades_profissionais', 'atuacao_profissional_id')
    # ### end Alembic commands ###
